### ISSUE TITLE
Auto disconnect after connecting to a jumpserver after a few seconds through ssh

### ISSUE THREAD

**Issue by songwing** [Eugeny/tabby#10131]
**Describe the problem**:
[A clear and concise description of what the bug is.]

**To Reproduce**:
[Steps to reproduce the behavior]

**Comment by icyfire** [comment]
same issue, need to fallback to 1.0.215.

**Comment by foundwant** [comment]
macos system, the same issue too, a very very serious bug!!!

**Comment by dazilang** [comment]
same issue

**Comment by GuanBaoxin** [comment]
same issue

**Comment by Eugeny** [comment]
Is it the same problem still happening with 1.0.218? I've specifically fixed the random disconnect issue in it.

**Comment by lhybdv** [comment]
> Is it the same problem still happening with 1.0.218? I've specifically fixed the random disconnect issue in it.

Yes, the problem still exists at 1.0.218, win11

**Comment by icyfire** [comment]
> Is it the same problem still happening with 1.0.218? I've specifically fixed the random disconnect issue in it.

Yes, it's still happening.

**Comment by Eugeny** [comment]
Could you run Tabby from another terminal with `RUST_LOG=debug` set and capture a log?

**Comment by jsrgjcy** [comment]
同样的问题！

**Comment by flyinghail** [comment]
I use a private key and MFA to log in to Jumpserver. In version 1.0.215, an MFA prompt window pops up at the bottom during connection, but in versions 1.0.216~1.0.219, a password prompt window appears at the top instead. Even if the correct password is entered, it shows "Authentication rejected."

**Comment by Eugeny** [comment]
@flyinghail MFA is fixed in 1.0.220

**Comment by ZhongmingFan** [comment]
same issue, auto disconnect after connecting to a jumpserver after a few seconds. v1.0.221 still not work, fallback to 215

**Comment by StandardStudent** [comment]
same issue

**Comment by flyinghail** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/157430?v=4&amp;size=80">@flyinghail](https://github.com/flyinghail) MFA is fixed in 1.0.220

I tested on 1.0.221, and the MFA issue has been resolved. The only remaining problem is that the connection automatically disconnects after a few seconds. Currently, only version 1.0.215 works properly.

**Comment by ltx666** [comment]
The latest version of the bug still exists, and 1.0.215 has been re-downloaded for use.

**Comment by Gavince** [comment]
he latest version of the bug still exists, and 1.0.215 has been re-downloaded for use.

**Comment by Eugeny** [comment]
Could you please capture an SSH debug log at the moment of a disconnect? Thanks

https://github.com/Eugeny/tabby/wiki/Capturing-a-debug-log-from-the-SSH-backend

**Comment by songwing** [comment]
> Could you please capture an SSH debug log at the moment of a disconnect? Thanks
> 
> https://github.com/Eugeny/tabby/wiki/Capturing-a-debug-log-from-the-SSH-backend
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/c7475aac04b72ccdbdab6d5f8abf505c824fdb625ef049acf2c773106c631bff/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Capturing a debug log from the SSH backend](https://github.com/Eugeny/tabby/wiki/Capturing-a-debug-log-from-the-SSH-backend)**A terminal for a more modern age. Contribute to Eugeny/tabby development by creating an account on GitHub.



`
[2025-02-06T15:51:57Z DEBUG russh::client] < msg type 98, seqn 212, len 31
[2025-02-06T15:51:57Z DEBUG russh::client::encrypted] channel_request: ChannelId(2) "keepalive@openssh.com"
[2025-02-06T15:51:57Z DEBUG russh::sshbuffer] > msg type 99, len 5
[2025-02-06T15:51:57Z DEBUG russh::client] disconnected Russh(IO(Custom { kind: UnexpectedEof, error: "early eof" }))
[2025-02-06T15:51:57Z DEBUG russh::client] drop session
[82279:0206/235157.977702:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[82279:0206/235157.978948:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
[82279:0206/235157.992798:ERROR:gl_display.cc(497)] EGL Driver message (Error) eglQueryDeviceAttribEXT: Bad attribute.
^C[82276:0206/235203.060905:ERROR:interface_endpoint_client.cc(722)] Message 5 rejected by interface blink.mojom.WidgetHost
[82276:0206/235203.060969:ERROR:interface_endpoint_client.cc(722)] Message 4 rejected by interface blink.mojom.WidgetHost
`

**Comment by flyinghail** [comment]
> Could you please capture an SSH debug log at the moment of a disconnect? Thanks
> 
> [Wiki: Capturing a debug log from the SSH backend](https://github.com/Eugeny/tabby/wiki/Capturing-a-debug-log-from-the-SSH-backend)
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/77213120/49dde400-c8c2-11e9-812a-e1407f1f42af"><img alt="" height="14" src="https://camo.githubusercontent.com/c7475aac04b72ccdbdab6d5f8abf505c824fdb625ef049acf2c773106c631bff/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Capturing a debug log from the SSH backend](https://github.com/Eugeny/tabby/wiki/Capturing-a-debug-log-from-the-SSH-backend)**A terminal for a more modern age. Contribute to Eugeny/tabby development by creating an account on GitHub.

```
[2025-02-07T13:18:42Z DEBUG russh::client::encrypted] channel_request: ChannelId(2) "keepalive@openssh.com"
[2025-02-07T13:18:42Z DEBUG russh::sshbuffer] > msg type 99, len 5
[2025-02-07T13:18:42Z DEBUG russh::client] disconnected Russh(IO(Custom { kind: UnexpectedEof, error: "early eof" }))
[2025-02-07T13:18:42Z DEBUG russh::client] drop session
[2025-02-07T13:18:42Z DEBUG russh_napi] russh-napi connecting to SshTransport(Mutex { data: Some(SocksProxy) })
[2025-02-07T13:18:42Z DEBUG russh::client] beginning re-key
```

**Comment by muzinian** [comment]
1.0.221 still exists. And the logs is :
```
[2025-02-08T07:31:36Z DEBUG russh::sshbuffer] > msg type 50, len 38
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 51, seqn 5, len 24
[2025-02-08T07:31:36Z DEBUG russh::client::encrypted] userauth_failure
[2025-02-08T07:31:36Z DEBUG russh::client::encrypted] remaining methods MethodSet([Password, PublicKey])
[2025-02-08T07:31:36Z DEBUG russh::client::encrypted] write_auth_request_if_needed: is_waiting = true
[2025-02-08T07:31:36Z DEBUG russh::sshbuffer] > msg type 50, len 63
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 52, seqn 6, len 1
[2025-02-08T07:31:36Z DEBUG russh::client::encrypted] userauth_success
[2025-02-08T07:31:36Z DEBUG russh::sshbuffer] > msg type 90, len 24
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 91, seqn 7, len 17
[2025-02-08T07:31:36Z DEBUG russh::client::encrypted] channel_open_confirmation
[2025-02-08T07:31:36Z DEBUG russh::sshbuffer] > msg type 98, len 56
[2025-02-08T07:31:36Z DEBUG russh::sshbuffer] > msg type 98, len 15
[2025-02-08T07:31:36Z DEBUG russh::sshbuffer] > msg type 98, len 39
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 99, seqn 8, len 5
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 9, len 69
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 10, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 11, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 12, len 38
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 13, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 14, len 45
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 15, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 16, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 17, len 36
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 18, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 19, len 42
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 20, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 21, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 22, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 23, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 24, len 46
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 25, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 26, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 27, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 28, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 29, len 46
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 30, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 31, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 32, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 33, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 34, len 46
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 35, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 36, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 37, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 38, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 39, len 49
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 40, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 41, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 42, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 43, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 44, len 50
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 45, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 46, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 47, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 48, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 49, len 55
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 50, len 20
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 51, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 52, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 53, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 54, len 55
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 55, len 21
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 56, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 57, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 58, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 59, len 31
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 60, len 21
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 61, len 16
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 62, len 10
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 63, len 13
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 64, len 25
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 65, len 14
[2025-02-08T07:31:36Z DEBUG russh::client] < msg type 94, seqn 66, len 21
[2025-02-08T07:31:37Z DEBUG russh::sshbuffer] > msg type 98, len 39
Update for version 1.0.221 is not available (latest version: 1.0.221, downgrade is disallowed).
[2025-02-08T07:31:41Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-02-08T07:31:41Z DEBUG russh::client] < msg type 82, seqn 67, len 1
[2025-02-08T07:31:46Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-02-08T07:31:46Z DEBUG russh::client] < msg type 82, seqn 68, len 1
[2025-02-08T07:31:51Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-02-08T07:31:51Z DEBUG russh::client] < msg type 82, seqn 69, len 1
[2025-02-08T07:31:56Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-02-08T07:31:56Z DEBUG russh::client] < msg type 82, seqn 70, len 1
[2025-02-08T07:32:01Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-02-08T07:32:01Z DEBUG russh::client] < msg type 82, seqn 71, len 1
[2025-02-08T07:32:06Z DEBUG russh::client] < msg type 98, seqn 72, len 31
[2025-02-08T07:32:06Z DEBUG russh::client::encrypted] channel_request: ChannelId(2) "keepalive@openssh.com"
[2025-02-08T07:32:06Z DEBUG russh::sshbuffer] > msg type 99, len 5
[2025-02-08T07:32:06Z DEBUG russh::client] disconnected Russh(IO(Custom { kind: UnexpectedEof, error: "early eof" }))
[2025-02-08T07:32:06Z DEBUG russh::client] drop session
```

**Comment by dong9205** [comment]
This is a serious problem. Is there a fix currently? Judging from the release time, it is because ssh2 was replaced with russh.

**Comment by dong9205** [comment]
I noticed that the time for each disconnection is basically around 30 seconds.

**Comment by TomCN0803** [comment]
Having the same issue :( 
Any progress or workaround?

**Comment by Alexios-cd** [comment]
I have encountered the same problem and have a headache. 
hope to solve it as soon as possible.

**Comment by aitianshi** [comment]
![Image](https://github.com/user-attachments/assets/f849b0aa-63ff-45d8-a8da-8f25e51f3f56)

if these parameters can be added in the "config file" tab, it would be nice. I believe it would and fix everyone problem.  @Eugeny

**Comment by dazilang** [comment]
Why hasn't such a serious bug been resolved for so long? Can't you show a bit more responsibility?

**Comment by aitianshi** [comment]
> Why hasn't such a serious bug been resolved for so long? Can't you show a bit more responsibility?

It's fully open source. So far, I have not seen any paid services for Tabby so it is entirely managed by the community. You are free and welcome to fork the project and continue to develop it. The owner and maintainers have no accountability towards users. See the [MIT License](https://github.com/eugeny/tabby?tab=MIT-1-ov-file#MIT-1-ov-file)

**Comment by dazilang** [comment]
> > Why hasn't such a serious bug been resolved for so long? Can't you show a bit more responsibility?
> 
> It's fully open source. So far, I have not seen any paid services for Tabby so it is entirely managed by the community. You are free and welcome to fork the project and continue to develop it. The owner and maintainers have no accountability towards users. See the [MIT License](https://github.com/eugeny/tabby?tab=MIT-1-ov-file#MIT-1-ov-file)

so sorry to say that.

**Comment by muzinian** [comment]
> ![Image](https://github.com/user-attachments/assets/6e665ce1-46c9-49a2-8771-ab0a810475ff)
> 
> Actually I have found it, just put 0 here and it shouldn't disconnect

version 1.0.222 change this config even worst.

**Comment by AlexWuYh** [comment]
![Image](https://github.com/user-attachments/assets/7fa32f8f-02ae-48a3-810c-f830d69dcd43)
same question

**Comment by black-ish** [comment]
I have the same issue, the disconnect happens after about 1 hour:
```
2025-03-16T15:16:39Z DEBUG russh::client] < msg type 82, seqn 733, len 1
[2025-03-16T15:16:43Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:16:43Z DEBUG russh::client] < msg type 82, seqn 712, len 1
[2025-03-16T15:16:44Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:16:44Z DEBUG russh::client] beginning re-key
[2025-03-16T15:16:44Z DEBUG russh::sshbuffer] > msg type 20, len 761
[2025-03-16T15:16:44Z DEBUG russh::client] < msg type 82, seqn 734, len 1
[2025-03-16T15:16:44Z DEBUG russh::client] < msg type 20, seqn 735, len 1048
[2025-03-16T15:16:44Z DEBUG russh::client::kex] negotiated algorithms: Names { kex: Name("curve25519-sha256"), key: Rsa { hash: Some(Sha256) }, cipher: Name("aes128-ctr"), client_mac: Name("hmac-sha1"), server_mac: Name("hmac-sha1"), server_compression: None, client_compression: None, ignore_guessed: false, strict_kex: false }
[2025-03-16T15:16:44Z DEBUG russh::sshbuffer] > msg type 30, len 37
[2025-03-16T15:16:44Z DEBUG russh::client] kex impl continues: ClientKex { cause: Rekey { strict: true, session_id: <32> }, state: "waiting for DH response" }
[2025-03-16T15:16:44Z DEBUG russh::client] < msg type 31, seqn 736, len 600
[2025-03-16T15:16:44Z DEBUG russh::client::kex] received server host key: Ok("<removed for obvious reasons>")
[2025-03-16T15:16:44Z DEBUG russh::sshbuffer] > msg type 21, len 1
[2025-03-16T15:16:44Z DEBUG russh::client] kex impl continues: ClientKex { cause: Rekey { strict: true, session_id: <32> }, state: "waiting for NEWKEYS" }
[2025-03-16T15:16:44Z DEBUG russh::client] < msg type 21, seqn 737, len 1
[2025-03-16T15:16:44Z DEBUG russh::client] kex impl has completed
[2025-03-16T15:16:44Z DEBUG russh::client] kex done
[2025-03-16T15:16:48Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:16:48Z DEBUG russh::client] < msg type 82, seqn 713, len 1
[2025-03-16T15:16:49Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:16:49Z DEBUG russh::client] disconnected Russh(IO(Custom { kind: UnexpectedEof, error: "early eof" }))
[2025-03-16T15:16:49Z DEBUG russh::client] drop session
[2025-03-16T15:16:53Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:16:53Z DEBUG russh::client] < msg type 82, seqn 714, len 1
[2025-03-16T15:16:58Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:16:58Z DEBUG russh::client] < msg type 82, seqn 715, len 1
[2025-03-16T15:17:03Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:03Z DEBUG russh::client] < msg type 82, seqn 716, len 1
[2025-03-16T15:17:08Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:08Z DEBUG russh::client] < msg type 82, seqn 717, len 1
[2025-03-16T15:17:13Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:13Z DEBUG russh::client] < msg type 82, seqn 718, len 1
[2025-03-16T15:17:18Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:18Z DEBUG russh::client] < msg type 82, seqn 719, len 1
[2025-03-16T15:17:23Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:23Z DEBUG russh::client] < msg type 82, seqn 720, len 1
[2025-03-16T15:17:28Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:28Z DEBUG russh::client] < msg type 82, seqn 721, len 1
[2025-03-16T15:17:33Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:33Z DEBUG russh::client] < msg type 82, seqn 722, len 1
[2025-03-16T15:17:38Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:38Z DEBUG russh::client] < msg type 82, seqn 723, len 1
[2025-03-16T15:17:43Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:43Z DEBUG russh::client] < msg type 82, seqn 724, len 1
[2025-03-16T15:17:48Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:48Z DEBUG russh::client] < msg type 82, seqn 725, len 1
[2025-03-16T15:17:53Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:53Z DEBUG russh::client] < msg type 82, seqn 726, len 1
[2025-03-16T15:17:58Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:17:58Z DEBUG russh::client] < msg type 82, seqn 727, len 1
[2025-03-16T15:18:03Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:18:03Z DEBUG russh::client] < msg type 82, seqn 728, len 1
[2025-03-16T15:18:08Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:18:08Z DEBUG russh::client] < msg type 82, seqn 729, len 1
[2025-03-16T15:18:13Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:18:13Z DEBUG russh::client] < msg type 82, seqn 730, len 1
[2025-03-16T15:18:18Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:18:18Z DEBUG russh::client] < msg type 82, seqn 731, len 1
[2025-03-16T15:18:23Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:18:23Z DEBUG russh::client] beginning re-key
[2025-03-16T15:18:23Z DEBUG russh::sshbuffer] > msg type 20, len 761
[2025-03-16T15:18:23Z DEBUG russh::client] < msg type 82, seqn 732, len 1
[2025-03-16T15:18:23Z DEBUG russh::client] < msg type 20, seqn 733, len 1093
[2025-03-16T15:18:23Z DEBUG russh::client::kex] negotiated algorithms: Names { kex: Name("curve25519-sha256"), key: Rsa { hash: Some(Sha256) }, cipher: Name("aes128-ctr"), client_mac: Name("hmac-sha1"), server_mac: Name("hmac-sha1"), server_compression: None, client_compression: None, ignore_guessed: false, strict_kex: false }
[2025-03-16T15:18:23Z DEBUG russh::sshbuffer] > msg type 30, len 37
[2025-03-16T15:18:23Z DEBUG russh::client] kex impl continues: ClientKex { cause: Rekey { strict: true, session_id: <32> }, state: "waiting for DH response" }
[2025-03-16T15:18:23Z DEBUG russh::client] < msg type 31, seqn 734, len 856
[2025-03-16T15:18:23Z DEBUG russh::client::kex] received server host key: Ok("<removed for obvious reasons>")
[2025-03-16T15:18:23Z DEBUG russh::sshbuffer] > msg type 21, len 1
[2025-03-16T15:18:23Z DEBUG russh::client] kex impl continues: ClientKex { cause: Rekey { strict: true, session_id: <32> }, state: "waiting for NEWKEYS" }
[2025-03-16T15:18:23Z DEBUG russh::client] < msg type 21, seqn 735, len 1
[2025-03-16T15:18:23Z DEBUG russh::client] kex impl has completed
[2025-03-16T15:18:23Z DEBUG russh::client] kex done
[2025-03-16T15:18:28Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-03-16T15:18:28Z DEBUG russh::client] disconnected Russh(IO(Custom { kind: UnexpectedEof, error: "early eof" }))
[2025-03-16T15:18:28Z DEBUG russh::client] drop session
```

**Comment by zhuchqun** [comment]
I also encountered the same situation. This problem still occurs in version 1.0.223

**Comment by flyinghail** [comment]
> > ![Image](https://github.com/user-attachments/assets/6e665ce1-46c9-49a2-8771-ab0a810475ff)
> > Actually I have found it, just put 0 here and it shouldn't disconnect
> 
> version 1.0.222 change this config even worst.

I got an error directly after trying to set keepalive to `0` on 1.0.223: `Authentication rejected`

Debug:
```
[2025-04-09T09:06:13Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-04-09T09:06:13Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-04-09T09:06:13Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-04-09T09:06:13Z DEBUG russh::sshbuffer] > msg type 80, len 27
[2025-04-09T09:06:13Z DEBUG russh::client] < msg type 6, seqn 2, len 17
[2025-04-09T09:06:13Z DEBUG russh::client::encrypted] waiting service request, Some(6) 6
[2025-04-09T09:06:13Z DEBUG russh::client::encrypted] enc: [0, 0, 0, 38, 50, 0, 0, 0, 7, 102, 101, 110, 103, 104, 97, 111, 0, 0, 0, 14, 115, 115, 104, 45, 99, 111, 110, 110, 101, 99, 116, 105, 111, 110, 0, 0, 0, 4, 110, 111, 110, 101]
[2025-04-09T09:06:13Z DEBUG russh::sshbuffer] > msg type 50, len 38
[2025-04-09T09:06:13Z DEBUG russh::client] disconnected Russh(IO(Custom { kind: UnexpectedEof, error: "early eof" }))
[2025-04-09T09:06:13Z DEBUG russh::client] drop session
```

**Comment by flyinghail** [comment]
I asked about this over at jumpserver and the response was: https://github.com/jumpserver/jumpserver/issues/15226#issuecomment-2814957574

> After a brief test, it appears that Tabby is unable to handle keepalive packets sent by SSH Server.JumpServer can be configured to disable the sending of keepalive heartbeat packets with the following configuration:

```
CLIENT_ALIVE_INTERVAL=0
```

**Comment by dage233** [comment]
这里存在一个在windows中的临时解决方案, 可用于1.0.223版本

1. windows系统安装ssh
2. 配置ssh config,添加jumpserver的配置
3. tabby新建配置,新建配置中,选择CMD为模板,命令替换为ssh登录

ssh登录示例: "C:\\Windows\\System32\\OpenSSH\\ssh.exe jms"

**Comment by flyinghail** [comment]
> And on Windows, you set these variable where?

`Jumpserver` will actively send `keepalive` message packets, `tabby >= 1.0.216` does not support this message, so the connection will be disconnected. The configuration `CLIENT_ALIVE_INTERVAL=0` is configured on the `Jumpserver` server side, not on the `tabby` client side.

**Comment by Eugeny** [comment]
I'm trying to reproduce it with Jumpserver and it's not happening - anything I need to set on the server side? I'm connecting directly as `user#user#uuid@jumpserver`

**Comment by skycyan** [comment]
> I'm trying to reproduce it with Jumpserver and it's not happening - anything I need to set on the server side? I'm connecting directly as `user#user#uuid@jumpserver`

My JumpServer version is v3.9.3, and no special configuration is required—default settings are sufficient.

When connecting via Tabby 1.0.223, the session disconnects after a few seconds. This appears to be related to Russh.

**Comment by ZhongmingFan** [comment]
> I'm trying to reproduce it with Jumpserver and it's not happening - anything I need to set on the server side? I'm connecting directly as `user#user#uuid@jumpserver`

Maybe you need to check if CLIENT_ALIVE_INTERVAL=0
The default configuration file is: /opt/jumpserver/config.txt

https://github.com/jumpserver/jumpserver/issues/15226#issuecomment-2814957574

@Eugeny

**Comment by wolgy** [comment]
I keep losing the connection to our jump server.I don't have the privileges to modify our jump server configuration. I tried setting the KeepAlive interval and count to zero, but it didn't work. It's really bothering me.

**Comment by luoxue03** [comment]
> I keep losing the connection to our jump server.I don't have the privileges to modify our jump server configuration. I tried setting the KeepAlive interval and count to zero, but it didn't work. It's really bothering me.

+1，please fix it

**Comment by AlexWuYh** [comment]
> > I keep losing the connection to our jump server.I don't have the privileges to modify our jump server configuration. I tried setting the KeepAlive interval and count to zero, but it didn't work. It's really bothering me.
> 
> +1，please fix it

+1, plsss！

**Comment by blight19** [comment]
> I keep losing the connection to our jump server.I don't have the privileges to modify our jump server configuration. I tried setting the KeepAlive interval and count to zero, but it didn't work. It's really bothering me.

+10086

**Comment by songwing** [comment]
V1.0.215 is enough for me though it‘s unfortunately become a swan song. However I'm still looking forward for an improvement on its initialization performance.

**Comment by blight19** [comment]
> V1.0.215 is enough for me though it‘s unfortunately become a swan song. However I'm still looking forward for an improvement on its initialization performance.

but i found that when i use mfa to login with V1.0.125 ,it says
 SSH  Please Enter MFA Code.
 SSH      Make sure `xauth` is installed on the remote side
with the newest version ,i can login ,but over 20s ,tabby close the session.
now i am use the cmd to login jumpserver via tabby.

**Comment by blight19** [comment]
> > V1.0.215 is enough for me though it‘s unfortunately become a swan song. However I'm still looking forward for an improvement on its initialization performance.
> 
> but i found that when i use mfa to login with V1.0.125 ,it says SSH Please Enter MFA Code. SSH Make sure `xauth` is installed on the remote side with the newest version ,i can login ,but over 20s ,tabby close the session. now i am use the cmd to login jumpserver via tabby.

i close X11 forwarding , and it works.

**Comment by jhusshini8** [comment]
I keep losing the connection to our jump server.I don't have the privileges to modify our jump server configuration. I tried setting the KeepAlive interval and count to zero, but it didn't work. It's really bothering me.

**Comment by blight19** [comment]
> I keep losing the connection to our jump server.I don't have the privileges to modify our jump server configuration. I tried setting the KeepAlive interval and count to zero, but it didn't work. It's really bothering me.

use version  V1.0.125.and close auto update, it works,

**Comment by jhusshini8** [comment]
> > I keep losing the connection to our jump server.I don't have the privileges to modify our jump server configuration. I tried setting the KeepAlive interval and count to zero, but it didn't work. It's really bothering me.
> 
> use version V1.0.125.and close auto update, it works,

Thanks for sharing this.

I can confirm a similar pattern on my side:
versions before the runssh migration are much more stable when connecting to JumpServer, while newer versions consistently lose the connection.

However, I’m a bit hesitant to recommend staying on very old versions like v1.0.125, because I’m not sure whether the Windows rz/sz file transfer issue (MD5 checksum mismatch) still exists in that release.

That issue is particularly risky in production environments, since file corruption is not always immediately visible.

So at the moment, it feels like a trade-off:

newer versions: unstable SSH sessions with JumpServer

older versions: potentially stable SSH, but unclear file integrity guarantees during rz/sz transfers

It would be really helpful if the maintainers could clarify:

which version definitively fixed the rz/sz MD5 issue on Windows

and whether a stable, supported workaround exists for JumpServer connections in recent releases

Thanks again for pointing out v1.0.125 — it’s useful data, but I’m not sure it’s safe enough to recommend broadly without clarification on file integrity.

**Comment by blight19** [comment]
> > > I keep losing the connection to our jump server.I don't have the privileges to modify our jump server configuration. I tried setting the KeepAlive interval and count to zero, but it didn't work. It's really bothering me.
> > 
> > 
> > use version V1.0.125.and close auto update, it works,
> 
> Thanks for sharing this.
> 
> I can confirm a similar pattern on my side: versions before the runssh migration are much more stable when connecting to JumpServer, while newer versions consistently lose the connection.
> 
> However, I’m a bit hesitant to recommend staying on very old versions like v1.0.125, because I’m not sure whether the Windows rz/sz file transfer issue (MD5 checksum mismatch) still exists in that release.
> 
> That issue is particularly risky in production environments, since file corruption is not always immediately visible.
> 
> So at the moment, it feels like a trade-off:
> 
> newer versions: unstable SSH sessions with JumpServer
> 
> older versions: potentially stable SSH, but unclear file integrity guarantees during rz/sz transfers
> 
> It would be really helpful if the maintainers could clarify:
> 
> which version definitively fixed the rz/sz MD5 issue on Windows
> 
> and whether a stable, supported workaround exists for JumpServer connections in recent releases
> 
> Thanks again for pointing out v1.0.125 — it’s useful data, but I’m not sure it’s safe enough to recommend broadly without clarification on file integrity.

my suggestion is use sftp instead of rz/sz and wait for the newer release to reslove it .  -_-

**Comment by flyinghail** [comment]
Hi, @Eugeny

As mentioned in this issue, when `russh` receives a keep-alive packet from the server, the SSH connection is terminated. This issue may have already been resolved in https://github.com/Eugeny/russh/pull/662.

Could you release a `tabby` version that uses the latest version of `russh` for testing?
