### ISSUE TITLE
Typing password can not login jump server

### ISSUE THREAD

**Issue by pci93** [Eugeny/tabby#10187]
Version: 1.0.218
Platform: macOS arm64 24.2.0
Plugins: trzsz
Frontend: xterm-webgl

After connecting to the jump server, I was unable to log in by typing the password,return authentication rejected, but pasting the password allowed me to log in. However, the SSH session was automatically disconnected after one minute.
The program runs normally in version 1.0.215.

**Comment by dongjiu0815** [comment]
Version: 1.0.219
Platform: macOS interl64 24C101
Plugins: trzsz
Frontend: xterm-webgl
Same problem as above and password cannot be saved

**Comment by Eugeny** [comment]
Should be fixed in the nightly once [this build](https://github.com/Eugeny/tabby/actions/runs/12817954508) passes.

**Comment by pci93** [comment]
The above issue still exists in the latest version 1.0.221. @Eugeny
