### ISSUE TITLE
ssh the cisco switch but failed with "WrongServerSig"

### ISSUE THREAD

**Issue by spermatozoa** [Eugeny/tabby#10289]
**Describe the problem**:
I try to ssh the cisco switch but failed with "WrongServerSig"
tabby version: v1.0.221~v1.0.218
![Image](https://github.com/user-attachments/assets/58cbeca9-7661-47e4-aa19-62945dec3466)

but I can connect it with tabby version under v1.0.216 and it's the same config

**To Reproduce**:

1. use tabby v1.0.221~v1.0.218
2. config:
        ciphers: aes192-ctr
        key exchange: diffie-hellman-group1-sha1
        hmac: hmac-sha1
        host key: ssh-rsa
3. ssh a cisco Nexus3064 switch

**Comment by Raging9** [comment]
me too

**Comment by viplo** [comment]
Hello works for me on a cisco Nexus9000 version 9.3(11)

**Comment by irhamdiamind** [comment]
![Image](https://github.com/user-attachments/assets/5707f02a-1a53-4079-a5d0-6bcc62514b82)

**Comment by Eugeny** [comment]
Should be fixed now in the nightly. It was caused by Tabby rejecting short (<2048bit) RSA host keys.

**Comment by acumeko** [comment]
> Should be fixed now in the nightly. It was caused by Tabby rejecting short (<2048bit) RSA host keys.

Just try the latest nightly for windows portable, still the same WrongServerSig

**Comment by spermatozoa** [comment]
> > Should be fixed now in the nightly. It was caused by Tabby rejecting short (<2048bit) RSA host keys.
> 
> Just try the latest nightly for windows portable, still the same WrongServerSig

@acumeko could you provide your cisco version and setting of connection?

**Comment by acumeko** [comment]
> [@acumeko](https://github.com/acumeko) could you provide your cisco version and setting of connection?

i know just cisco 9407 with 10Gb port

**Comment by deuxyeux** [comment]
Same problem with Unifi access points.

**Comment by acumeko** [comment]
1.0.223 Nightly still the same WrongServerSig.
I guess the different as below
[](https://imgops.com/1hr-tempcache/userUploadTempCache_ip211.75.165.114_utc_20250310-011747_IMG8101.jpg)
