### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by viplo** [Eugeny/tabby#10305]
Hello,
I'm trying to switch to tabby but for now I'm having tow issues.
The first one is a Fortinet Firewall, only one because others works fine
Fortinet Fortigate 101F - v7.2.8 build1639 (Mature)
When I log from a local ssh from tabby it works fine but when I launch a saved session I have this error
 SSH  Connecting to firewall-1
 X  WrongServerSig

The second is a ESXi version 7.0.0.
Same situation, I can connect througt a tabby ssh  but not a tabby saved session.
The error is different:
 SSH  Connecting to esx-7.0
 SSH  Host key fingerprint:
 SSH   ssh-rsa  SHA256:xxx 
 X  Authentication rejected

For both I have selected all ciphers.

My Tabby version is
Version: 1.0.221
Platform: Linux x64 6.8.0-53-generic
Plugins: none
Frontend: xterm-webgl

Best regards

**Comment by mort666** [comment]
Hi, just a suggestion, try using build 1.0.215 which is the last one before they changed the ssh library in the backend and see if you can connect using that version. If you can, then this is another symptom of the broken ssh lib. As highlighted by #10179 #10117 #10245 just to reference a couple of the issues about ti..

**Comment by viplo** [comment]
Hello,
Thanks @mort666 for your answer.
For the FW I have the same error but for the esx, the error change from "Authentication rejected" to " All configured authentication methods failed"
I already delete the fingerprint in my .ssh/config file.
Anyway, all the other connection I have works so I'm still confident to this tool.

May be one time in the future update it will be fixed.
Cheers

**Comment by viplo** [comment]
I'm was on version 1.0.215 and back to version 1.0.221 no solution yet, waiting for futur upgrade

**Comment by mort666** [comment]
Yeah, no solution yet it seems, frankly I had to drop tabby this week due to an semi unrelated issue with the electron 32 and changes in 32.3 on Linux which basically broke input for important stuff like copy & paste... So I've basically switched to ghostty + tssh, basically 'duct taped' a tabbed ssh client together with ghostty and tssh and creative use of both configs and a lot of swearing..

**Comment by aqvador** [comment]
The issue has been resolved in version 1.0.223!

**Comment by ogritskov-arch** [comment]
> The issue has been resolved in version 1.0.223!

I'm on version 1.0.230 but can't connect to ESXI 7.x from Tabby, immidiate "Authentication rejected" doe not matter what I do, but can connect from any other SSH client no issues.

**Comment by viplo** [comment]
in version 1.0.233, issue still here...
I'm sad because I have to look for an alternative of tabby

**Comment by Bob2345de** [comment]
same here no joy on 1.0.234.
