### ISSUE TITLE
Authentication rejected

### ISSUE THREAD

**Issue by chrisss00** [Eugeny/tabby#10354]
Version: 1.0.222
Platform: Windows x64 10.0.22631
Plugins: none
Frontend: xterm-webgl

![Image](https://github.com/user-attachments/assets/a342d59b-d148-4e18-ba61-111d20cf23ca)

**Comment by toffelwurst** [comment]
Rollback to 1.0.221 it seems to be a bug in 1.0.222

https://github.com/Eugeny/tabby/issues/10347

**Comment by Eugeny** [comment]
Please try the latest nightly build, it should be fixed there.

**Comment by jiaopengzi** [comment]
> Please try the latest nightly build, it should be fixed there.

Thank you very much for your reply. However, after downloading `tabby-1.0.223-nightly.0-setup-x64.exe`, I still encounter the same issue.

**Comment by sangnigege** [comment]
We encountered the same issue, and after my attempts, rolling back to version 1.0.221 indeed worked. The previous response was correct.

**Comment by Eugeny** [comment]
I've updated the build, could you give it another try?

**Comment by Eugeny** [comment]
Merging with #10347

**Comment by jiaopengzi** [comment]
> I've updated the build, could you give it another try?

It's great. `tabby-1.0.223-nightly.0-setup-x64.exe` and `tabby-1.0.223-nightly.0-portable-x64` It's working.
Thank you very much.
