### ISSUE TITLE
SSH connection fails with "Cannot read properties of undefined (reading 'filter')" after upgrading to v1.0.224+

### ISSUE THREAD

**Issue by rejarevaldy** [Eugeny/tabby#10688]
**Describe the problem**:
After upgrading Tabby from `v1.0.223` to newer versions (`v1.0.224` and `v1.0.227`), SSH connections fail with the following error:

```
SSH  Connecting to OJT Jats
X  Cannot read properties of undefined (reading 'filter')
```

This issue does not occur in version `v1.0.223`.

**To Reproduce**:

1. Open Tabby `v1.0.224` or `v1.0.227`.
2. Select a saved SSH profile or enter an address to connect. 

<img width="466" height="133" alt="Image" src="https://github.com/user-attachments/assets/1cef0453-f722-4894-b712-a1254c3f5899" />

3. Attempt to connect.
4. Observe the error: `Cannot read properties of undefined (reading 'filter')`.

**Expected behavior**:
SSH should connect successfully, as it does on version `v1.0.223`.

**Actual behavior**:
SSH connection fails with `Cannot read properties of undefined (reading 'filter')`.

**Environment**:

* **Tabby version:** 1.0.224, 1.0.227 (bug occurs)
* **Last working version:** 1.0.223
* **OS:** Debian

**Comment by frussane** [comment]
Have the same problem, we really could use a fix and seems like a top priority bug.
Any workaround other than using 1.0.223?

**Comment by WanderingZombie** [comment]
In Windows 10 all SSH sessions fail to reconnect with "Cannot read properties of undefined (reading 'filter')", even after update to 1.0.228 today.

**Comment by tomazz75** [comment]
I upgraded to 1.0.229 today and can't connect to any saved SSH session, same error "Cannot read properties of undefined (reading 'filter')". How come this isn't fixed?

EDIT: I can't connect to "old" sessions still opened, with "Reconnect" button.  If I close them and open new session then it works. 
@Eugeny wouldn't this be considered critical bug?

**Comment by alexcool2016** [comment]
Me too, any idea?

 SSH  Connecting to app server
 SSH   !  Agent auth selected, but no running Agent process is found
 SSH   !  Agent auth selected, but no running Agent process is found
 X  Cannot read properties of undefined (reading 'filter')

**Comment by Gelix** [comment]
Yeah, this bug is still here, I'm stuck on 1.0.223 on all my workstations.  Debug Console output
```
C:\Program Files\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:9386 SSH session initialization failed TypeError: Cannot read properties of undefined (reading 'filter')
    at SSHSession.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:8287:72)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:6809:24)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:127:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:171:47)
    at drainMicroTaskQueue (zone.js:581:35)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:21)
    at invokeTask (zone.js:1631:18)
    at globalCallback (zone.js:1662:29)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1695:16)
    at HTMLButtonElement.sentryWrapped (helpers.ts:87:17)
(anonymous) @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:9386
rejected @ C:\Program Files\Tabby\resources\builtin-plugins\tabby-ssh\dist\index.js:6816
invoke @ zone.js:368
onInvoke @ ng_zone.ts:423
invoke @ zone.js:367
run @ zone.js:127
(anonymous) @ zone.js:1257
invokeTask @ zone.js:402
onInvokeTask @ ng_zone.ts:408
invokeTask @ zone.js:401
runTask @ zone.js:171
drainMicroTaskQueue @ zone.js:581
invokeTask @ zone.js:487
invokeTask @ zone.js:1631
globalCallback @ zone.js:1662
globalZoneAwareCallback @ zone.js:1695
sentryWrapped @ helpers.ts:87

```

**Comment by ocpinfo** [comment]
Same error in 1.0229, Any solution?

**Comment by Gelix** [comment]
I was able to fix mine with this patch.  Basically it is trying to call filter on the newly added in 1.124 in algorithms.ts " [SSHAlgorithmType.COMPRESSION]: russh.getSupportedCompressionAlgorithms().reverse()," 

```
diff --git a/tabby-ssh/src/session/ssh.ts b/tabby-ssh/src/session/ssh.ts
index dc39d442..e9ba8d01 100644
--- a/tabby-ssh/src/session/ssh.ts
+++ b/tabby-ssh/src/session/ssh.ts
@@ -352,7 +352,9 @@ export class SSHSession {
 
         const algorithms = {}
         for (const key of Object.values(SSHAlgorithmType)) {
+             if(key !== SSHAlgorithmType.COMPRESSION) { 
             algorithms[key] = this.profile.options.algorithms![key].filter(x => supportedAlgorithms[key].includes(x))
+             }
         }
 
         // eslint-disable-next-line @typescript-eslint/init-declarations
```

**Comment by rejarevaldy** [comment]
> I was able to fix mine with this patch. Basically it is trying to call filter on the newly added in 1.124 in algorithms.ts " [SSHAlgorithmType.COMPRESSION]: russh.getSupportedCompressionAlgorithms().reverse(),"
> 
> ```
> diff --git a/tabby-ssh/src/session/ssh.ts b/tabby-ssh/src/session/ssh.ts
> index dc39d442..e9ba8d01 100644
> --- a/tabby-ssh/src/session/ssh.ts
> +++ b/tabby-ssh/src/session/ssh.ts
> @@ -352,7 +352,9 @@ export class SSHSession {
>  
>          const algorithms = {}
>          for (const key of Object.values(SSHAlgorithmType)) {
> +             if(key !== SSHAlgorithmType.COMPRESSION) { 
>              algorithms[key] = this.profile.options.algorithms![key].filter(x => supportedAlgorithms[key].includes(x))
> +             }
>          }
>  
>          // eslint-disable-next-line @typescript-eslint/init-declarations
> ```

Thanks for sharing. I downloaded the latest version (1.0.230), and the issue is already fixed.

**Comment by Gelix** [comment]
Very interesting, my fix was against the 1.0.230 version which was most definitely still not working for me.  Go figure?

**Comment by theodor-codrianu** [comment]
well to me it happened on .230 
but .. if you are like me you had connections opened when you upgraded 
as this app works have to had some cache at hand so long story short 
- close all connections
- restart tabby 
no more " Cannot read properties of undefined (reading 'filter')" 
at least for me .....
