### ISSUE TITLE
Freeze/unresponsive UI on large outputs

### ISSUE THREAD

**Issue by max1c** [Eugeny/tabby#3604]
I am experiencing a permanent freeze and high CPU usage when using 'less' or 'grep' with lots of output to the terminal. This happens on multiple different machines and has been an ongoing issue in many different versions of Terminus. This is still an issue with Alpha 135. A recent example to reproduce:

$ git clone https://github.com/Kinggerm/GetOrganelle
$ less GetOrganelle/README.md

And terminus has been completely frozen with constant ~30% CPU usage. The only resolution is to end the task through the task manager.

**Comment by dargow** [comment]
I also observe this problem

**Comment by clarkwang** [comment]
Did some testing and found it's because Terminus would save **ALL** terminal output to memory.

It can be reproduced like this:

~~~
$ od -N 1048576 /dev/urandom > file    # this generates a text file of ~4MB
$ for i in {1..20}; do cat file; done  # repeat this to eat more memory
~~~

With Windows Task Manager you can see Terminus' memory usage keeps increasing and quite often the Terminus Tab stops responding.

![image](https://user-images.githubusercontent.com/157076/111426724-0c54dc00-8730-11eb-819a-fd95ce2d80b0.png)

We should limit the output buffer with a default value like in PuTTY:

![image](https://user-images.githubusercontent.com/157076/111427687-6c984d80-8731-11eb-8e97-5536afe04430.png)

**Comment by Eugeny** [comment]
I've been able to reproduce this with @mariusa's repro two times and suddenly it's gone and isn't happening anymore (Windows and macOS). The scrollback buffer isn't infinite and is instead limited to 100k rows.

Any pointers on how to reproduce it more reliably are appreciated :+1:

**Comment by clarkwang** [comment]
May be fixed by some recent code change? Can we have a new build to give it a try?

**Comment by clarkwang** [comment]
> P.S. it can't be just the output volume - I'm routinely using `hexdump /dev/urandom` to test that

To me `hexdump /dev/urandom` is not fast enough. You can try my steps in  https://github.com/Eugeny/terminus/issues/3604#issuecomment-800847004

**Comment by Eugeny** [comment]
Sure - the nightly links are in the README:

* https://nightly.link/Eugeny/terminus/workflows/windows/master
* https://nightly.link/Eugeny/terminus/workflows/macos/master
* https://nightly.link/Eugeny/terminus/workflows/linux/master

also check out this experimental branch that introduces PTY flow control:

* https://nightly.link/Eugeny/terminus/workflows/windows/remote-pty
* https://nightly.link/Eugeny/terminus/workflows/macos/remote-pty
* https://nightly.link/Eugeny/terminus/workflows/linux/remote-pty

**Comment by clarkwang** [comment]
Managed to download the nightly build <sup>(my company's DNS even cannot resolve `nightly.link`)</sup> but it does not work for me (on win10). Tried a few times. I can see 4 Terminus processes in Task Manager but the UI never shows up.

**Comment by max1c** [comment]
I think this has something to do with the color highlighting. Because even just switching to a screen window that I had with a bunch of output from grep (that was not running anymore) completely froze Terminus.

**Comment by clarkwang** [comment]
Update for v1.0.136 (on win10) with the following steps:

~~~
$ hexdump -n 1048576 -C /dev/urandom > file    # this generates a text file of ~5 MB
$ for i in {1..100}; do cat file; done         # repeat this to eat more memory
~~~

* The memory usage does not keep increasing. For me it stabilized at ~500MB.
* But `for i in {1..100}; do cat file; done` can always freeze the Tab.

**Comment by max1c** [comment]
I can report that 1.0.136 did not freeze Terminus on the screen session with a grep search I had opened specifically to test this.

**Comment by rstarkov** [comment]
All it took for mine to freeze was typing "dir". It was the very first command I ever typed. It was Alpha 136 on Win10, using clink and ConPTY. The output wasn't long, no more than 30 lines - I only got to see ~15. It froze halfway through a line.

I tried again without clink, then I tried again after disabling ConPTY. It froze every time after just a few keypresses.

**Comment by clarkwang** [comment]
> All it took for mine to freeze was typing "dir". It was the very first command I ever typed. It was Alpha 136 on Win10, using clink and ConPTY. The output wasn't long, no more than 30 lines - I only got to see ~15. It froze halfway through a line.
> 
> I tried again without clink, then I tried again after disabling ConPTY. It froze every time after just a few keypresses.

Just tried alpha 136 on win10.

* With ConPTY enabled, all profiles work fine.
* With ConPTY disabled, all profiles (cmd/stock, cmd/clink, powershell, cycgwin) would freeze after it shows the prompt. I cannot input anything. Seems like it can output but cannot input.

**Comment by clarkwang** [comment]
> Just tried alpha 136 on win10.
> 
> * With ConPTY enabled, all profiles work fine.
> * With ConPTY disabled, all profiles (cmd/stock, cmd/clink, powershell, cygwin) would freeze after it shows the prompt. I cannot input anything. Seems like it can output but cannot input.

Did not repro this with 1.0.137.

**Comment by Eugeny** [comment]
A136 had another specific bug that caused the output to be cut off (not related to this issue).

@max1c could you please try and see if A137 now works as expected?

**Comment by max1c** [comment]
> A136 had another specific bug that caused the output to be cut off (not related to this issue).
> 
> @max1c could you please try and see if A137 now works as expected?

Nope. Just tested running usual grep and it froze almost immediately and is stuck at ~8% CPU usage. If there is a way to produce some logs let me know how.

**Comment by Eugeny** [comment]
Does 8% correspond to 100% of a single core on your system?

**Comment by max1c** [comment]
Ok, so what's interesting about this time. Is once killed the process and re-connected to my screen session it actually finished the grep run and didn't freeze immediately again. Previously, it would insta freeze again on screen session re-connect. Doesn't look like it's stuck on a single core either but I'm not sure. It's basically using 8-9% going up and down. 
![image](https://user-images.githubusercontent.com/11587156/116006204-20fe7c80-a5d8-11eb-82f6-e8704ff575dc.png)

**Comment by clarkwang** [comment]
With 1.0.137 I can still repro the Tab freeze using steps in comment https://github.com/Eugeny/terminus/issues/3604#issuecomment-817505373 .

**Comment by Eugeny** [comment]
I've managed to catch this problem live and debug into the Webkit as far as I could before it crashed. If hangs while running some regex against the whole contents of the terminal. As far as I see, the only regex-related thing we run against the output on our side is progress detection and clickable-links plugin.

Could you all please try disabling progress detection (`terminal.detectProgress` to `false` in the config) and disabling the clickable-links plugin (if you have it installed)?

**Comment by max1c** [comment]
I just tried a few times in a row and it looks like disabling clickable-links fixes the freeze. I re-enabled it a few times and it froze each time.

**Comment by clarkwang** [comment]
> I've managed to catch this problem live and debug into the Webkit as far as I could before it crashed. If hangs while running some regex against the whole contents of the terminal. As far as I see, the only regex-related thing we run against the output on our side is progress detection and clickable-links plugin.
> 
> Could you all please try disabling progress detection (`terminal.detectProgress` to `false` in the config) and disabling the clickable-links plugin (if you have it installed)?

For my repro in https://github.com/Eugeny/terminus/issues/3604#issuecomment-817505373 I have already disabled `terminal.detectProgress` and I did not install 3rd-party plugins.

**Comment by fraynaud33** [comment]
Hello, I reproduce this issue to easily : Terminus version 1.0.138
```
curl www.google.fr
```
and it freeze after prompt.
```
curl --output test.txt www.google.fr
more test.txt
```
In this case it freeze after having more command.
It's when Terminus display the text than it freeze.
With ou without having Use ConPTY enabled.

**Comment by Eugeny** [comment]
I've just pushed clickable-links plugin update that limits the maximum regex length - please test!

**Comment by max1c** [comment]
> I've just pushed clickable-links plugin update that limits the maximum regex length - please test!
Just tested, still freezes. It slows down then becomes basically unresponsive and then permanently freezes.

**Comment by clarkwang** [comment]
With 1.0.139 I can still repro https://github.com/Eugeny/terminus/issues/3604#issuecomment-817505373 (`terminal.detectProgress` disabled and no 3rd-party plugins installed).

**Comment by max1c** [comment]
> Update for v1.0.136 (on win10; ssh'ed to a linux) with the following steps:
> 
> ```
> $ hexdump -n 1048576 -C /dev/urandom > file    # this generates a text file of ~5 MB
> $ for i in {1..100}; do cat file; done         # repeat this to eat more memory
> ```
> 
> * The memory usage does not keep increasing. For me it stabilized at ~500MB.
> * But `for i in {1..100}; do cat file; done` can always freeze the Tab.

I just tested this again with clickable-links 4.1.0 and 10.144 release and I cannot reproduce the freeze anymore. It slows down using this method but still chugs through with high cpu usage. Also, the grep searches I had freezes with don't happen anymore either.

**Comment by Eugeny** [comment]
@max1c thanks! `clickable-links` v4.1.0 fixes an issue in the URL regexp which caused [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html) on some inputs - I've only got lucky recently and found a 100% reliable repro for this. So that should take care of at least a part of this issue. 

@clarkwang could you perhaps check to see if you see any improvement with v144? (I know you said you aren't using any plugins, but perhaps recent xterm updates have improved the situation somewhat)

**Comment by clarkwang** [comment]
Version: 1.0.145
Platform: win32 10.0.17763
Plugins: none
**detectProgress: false**

SSH'ed to a Linux and:

~~~
$ hexdump -n 1048576 -C /dev/urandom > file    # this generates a text file of ~5 MB
$ for i in {1..100}; do cat file; done         # repeat this to eat more memory
~~~

* Very quickly the Tab will freeze but mem usage keeps increasing. I killed it when it reached 1.5GB.
* What's worse than before is that the whole Tabby app freezes.

**Comment by thorus90** [comment]
Also noticing this issue with rsync with a lot of files. version: 1.0.169

**Comment by Eugeny** [comment]
This has been improved in recent versions.

**Comment by ghostrider-reborn** [comment]
![image](https://user-images.githubusercontent.com/34226885/232020541-a8fee223-60b2-4bfb-b185-07e0091100a4.png)
![image](https://user-images.githubusercontent.com/34226885/232020823-2884a093-433e-4aef-b595-7090defc80c2.png)

Still facing this on latest versions, I'm on Alpha 196. Tabby is frozen with high CPU usage after a large output from `ripgrep`.
