### ISSUE TITLE
why upload a file will make it have executable permissions

### ISSUE THREAD

**Issue by echovanity** [Eugeny/tabby#4141]
Version: 1.0.144
Platform: win32 10.0.19043
Plugins: none

when i update tabby from v1.0.137(terminus) ,the "file transfers" has changed , and when i download a file without executable permissions，it  as usual, but when i upload this file，will make it have executable permissions, and i cannot but use "chmod 644" make it non-executable， i wonder why will this ,and how can i change it， where can i ？looking forward to ur reply

**Comment by Eugeny** [comment]
Do you mean SFTP or Zmodem?

**Comment by echovanity** [comment]
> Do you mean SFTP or Zmodem?

yea, ZModem ,i use the command “sz” and "rz"

**Comment by echovanity** [comment]
hey bro, i have been upgrade to v1.0.146, but the problem remain, mode for Zmodem

**Comment by Eugeny** [comment]
It's fixed in the nightly build.

**Comment by fangawb** [comment]
i have been upgrade to v1.0.168, but the problem remain, mode for Zmodem
