### ISSUE TITLE
Cannot establish SSH connection to Cisco switch (Tabby 1.0.146)

### ISSUE THREAD

**Issue by rdapaz** [Eugeny/tabby#4209]
Cannot establish SSH sessions with Cisco switches C9300 and C9500 running IOS 16.10.1 from Tabby 1.0.146 running on Windows 10.  It works fine with a Palo Alto firewall but just hangs with the Cisco switches.

**Comment by Eugeny** [comment]
Could you please try the latest nightly? There are a few fixes for that inparticular

**Comment by rdapaz** [comment]
Thanks heaps for your prompt response and excellent work on this project!!! I am absolutely in love with Tabby!!!

**Comment by Eugeny** [comment]
Thanks, does this mean it worked? :D

**Comment by sectorogo** [comment]
Try the latest release. It should be fixed.

**Comment by cgfcrc** [comment]
I still have an issue signing into Cisco Switches using SSH/Tabby. I am on version 1.0.207. Is there another specific build I should be using or configuration?
