### ISSUE TITLE
The screen does not refresh in real time when it run on powershell

### ISSUE THREAD

**Issue by lost22git** [Eugeny/tabby#5673]
|app|version|
|:---|---:|
|tabby |  1.0.168|
|powershell | 7.2.1|
|windows | win11|

![屏幕截图 2022-02-06 181152](https://user-images.githubusercontent.com/65008815/152676287-762bbc56-5b99-4481-b421-58116633e8e2.png)

**Comment by Eugeny** [comment]
This should be fixed in the nightly build - could you give it a try?

**Comment by test210820** [comment]
> This should be fixed in the nightly build - could you give it a try?

The problem seems to still exist...

![屏幕截图 2022-02-06 185622](https://user-images.githubusercontent.com/65008815/152677659-4af3f1b9-7fc6-4412-8a8f-9d186f382d0d.png)


![屏幕截图 2022-02-06 185649](https://user-images.githubusercontent.com/65008815/152677649-8d58097f-419f-4702-b5f1-c167202cd95e.png)

![屏幕截图 2022-02-06 185348](https://user-images.githubusercontent.com/65008815/152677674-7dbea80e-d284-4c77-9e98-31262f68abe9.png)

**Comment by Eugeny** [comment]
Thanks. Could you also check whether the WebGL frontend has the same problem?

**Comment by test210820** [comment]
> Thanks. Could you also check whether the WebGL frontend has the same problem?

same problem
