### ISSUE TITLE
SSH password is not getting saved and every time it asks for the password..

### ISSUE THREAD

**Issue by AnilaSri** [Eugeny/tabby#9320]
**Describe the problem**:
The password stored is not being used for ssh connection

**To Reproduce**:
1. Create a new profile
2. Select ssh connection
3. Give the IP of the host and select the password as the authentication method
4. Set the password and save it
5. When the host is started, I'm getting the following error:

 SSH  Connecting to <IP>
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-nistp256  l26xRjU+QVBxgsqh+3hVtb3q2H4v0GdoNW8WxlE1kms= 

 SSH  Connecting to <IP>
 SSH  Host key fingerprint:
 SSH   ecdsa-sha2-nistp256  l26xRjU+QVBxgsqh+3hVtb3q2H4v0GdoNW8WxlE1kms= 
 X  All configured authentication methods failed
 I have verified the username and password and they are correct

**Comment by Eugeny** [comment]
Should be fixed in the nightly once [this build](https://github.com/Eugeny/tabby/actions/runs/12817954508) passes.

**Comment by kernelkraut** [comment]
I'm afraid this issue still persists. I have to enable interactive on a number of systems or it just fails.

Using version 1.0.223

**Comment by not-amplify** [comment]
> I'm afraid this issue still persists. I have to enable interactive on a number of systems or it just fails.
> 
> Using version 1.0.223

Im getting this issue too, but my conclusion is the OS is the issue. ive attempted multiple versions, including one that i know works on an alternate device, yet passwords do not save. any ideas would be appreciated.

**Comment by not-amplify** [comment]
using a vault solves the issue, just remeber the vault for 7 days i guess

**Comment by zdev-code** [comment]
Saved passwords doesn't work for Unifi devices, have to pick interactive and confirm the password.
