### ISSUE TITLE
Tab empty until I click mouse / switch app and come back

### ISSUE THREAD

**Issue by francisdb** [Eugeny/tabby#9556]
**Describe the problem**:

When opening a new tab I get a blank tab, only after clicking with the mouse in the tab contents do I see the shell and can I start typing.

**To Reproduce**:

`Tabby 1.0.207`
`x86_64 x86_64 GNU/Linux`
`Ubuntu 23.10`
Running `Wayland` session
`Ohmyzsh`

1. Open tabby, shows welcome tab
2. Click `+` to create a new tab
3. The tab is empty and mentions `User default`
  ![image](https://github.com/Eugeny/tabby/assets/161305/24f36af2-3667-4e37-9173-ad0d80c1e39c)
4. Click in the empty space or go to a different app and back to tabby
  ![image](https://github.com/Eugeny/tabby/assets/161305/be988f4c-d2f7-452d-aeac-a0cc32c3626c)
5. The shell and cursor appears

**Comment by Xenolphthalein** [comment]
I have the same issue and wanted to add that it does not make a difference using other shells (bash, zsh, sh).
It only appears on Linux, I use Manjaro with GNOME. Windows builds are fine.

**Comment by Xenolphthalein** [comment]
I just found out that disabling the GPU acceleration in the settings is preventing this issue.

**Comment by francisdb** [comment]
Fixed itself in Ubuntu 24.04 (Wayland) for me

**Comment by stark1tty** [comment]
I am also having this issue.

**Comment by Marceau-h** [comment]
Still having the issue on fedora 40, and with multiple computers (2 \w dedicated nvidia gc and one intel igpu)

**Comment by PaperL** [comment]
Still have this bug on
MacOS 15.3 (24D60)
Apple M3 Chip
Tabby 1.0.221
Opening zsh / remote ssh in zsh
