### ISSUE TITLE
Issue with Jump Host / Bastion host

### ISSUE THREAD

**Issue by phpandrew** [Eugeny/tabby#9580]
**Describe the problem**:
I have 2 profiles setup. 
The first connects directly to server1, and forwards the port to 127.0.0.1:55550

The second connection over ssh connects directly to 127.0.0.1:55550

These work fine if I open the first connection, then the second.

I setup the second connection to use Jump Host, selecting the first profile.

Doing so results in an error:
"Could not set up port forward on [profile 1]

**To Reproduce**:
1) Create a direct connection to server
2) setup port forwarding on this first profile to Local, 127.0.0.1:55550 -> 11.22.33.44:22 (secondary server)
3) Setup a secondary profile that directly connects over ssh to 127.0.0.1:55550
4) on second profile, select Jump Host and select the first profile.
5) Open the second profile to reproduce error

**Comment by ruanwenjun** [comment]
I also meet this problem, is there any solution?

**Comment by phpandrew** [comment]
> I also meet this problem, is there any solution?

I ended up switching to MoboXterm shortly after. Still using it

**Comment by ruanwenjun** [comment]
> > I also meet this problem, is there any solution?
> 
> I ended up switching to MoboXterm shortly after. Still using it

I use macos 😭

**Comment by Eugeny** [comment]
Should be fixed in the nightly once [this build](https://github.com/Eugeny/tabby/actions/runs/12817954508) passes.

**Comment by omarmohsen** [comment]
I still face this issue in the latest version 1.0.223
 SSH   X  Could not set up port forward on omar@X.X.X.X (.ssh/config)
 X  SendError

**Comment by Jameslu041** [comment]
> I still face this issue in the latest version 1.0.223 SSH X Could not set up port forward on [omar@X.X.X.X](mailto:omar@X.X.X.X) (.ssh/config) X SendError

facing the same problem after upgrade mac os to 15.6 ...

**Comment by undefined443** [comment]
I solved the problem by disabling `Reuse session for multiple tabs` in the profile.
